export { default as Header } from './header/Header'
// export { default as Footer } from './!!__footer/Footer'
// export { default as LoginForm } from '../pages/login/LoginForm'
// export { default as ResetPasswordForm } from '../pages/login/ResetPasswordForm'
// export { default as CreateAccountForm } from '../pages/login/CreateAccountForm'
// export { default as ChangePasswordForm } from '../pages/login/ChangePasswordForm'
export { default as SideNavigationMenu } from './side-navigation-menu/SideNavigationMenu'
